version: '3.4'

services:
  oracle_rest_data_service:
    container_name: oracle_rest_data_service
    restart: always
    ports:
       - "8521:1521"
       - "8500:5500"
       - "8023:8080"
       - "9043:8443"
    environment:
       - ORACLE_PWD=E
    networks:
       - ords_net
  
  identityDb:
    container_name: identityDb
    environment:
       - SA_PASSWORD=Identity2024@Pass
       - ACCEPT_EULA=Y
    restart: always
    ports:
       - "1433:1433"
    networks:
      - identity_net

  elasticsearch:
    container_name: elasticsearch
    restart: always
    ports:
       - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    restart: always
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
        - ELASTICSEARCH_URL=http://localhost:9200
    networks:
        - elastic

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - 5672:5672
       - 15672:15672
    volumes:
       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
       - rabbitmq_go_net

  portainer:
    container_name: portainer
    restart: always
    ports:
       - "8098:8000"
       - "9000:9000" 
    volumes:
       -  /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data


  branch.api:
    container_name: branch.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OracleSettings:OrdsDatabaseUrl=http://oracle_rest_data_service:8080"
      - "OracleSettings:DatabaseUser=ordsuser"
      - "OracleSettings:DatabaseTableName=branch"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "IdentityUrl=http://identity.api"
      - "GrpcSettings:BankUrl=http://bank.grpc"
    depends_on:
      - oracle_rest_data_service
      - elasticsearch
      - identity.api
    ports:
      - "8000:80"
    networks:
      - elastic
      - ords_net
      - gateway_net

  branch.grpc:
    container_name: branch.grpc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OrdsSettings:Uri=http://oracle_rest_data_service:8080/ords/ordsuser/branch/"
      - "OrdsSettings:DatabaseUrl=http://oracle_rest_data_service:8080"
      - "OrdsSettings:DatabaseUser=ordsuser"
      - "OrdsSettings:DatabaseTableName=branch"
    depends_on:
      - oracle_rest_data_service
    ports:
      - "8001:80"
    networks:
      - ords_net
      - gateway_net

  account.api:
    container_name: account.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OracleSettings:OrdsDatabaseUrl=http://oracle_rest_data_service:8080"
      - "OracleSettings:DatabaseUser=ordsuser"
      - "OracleSettings:DatabaseTableName=account"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672/"
      - "GrpcSettings:BranchUrl=http://branch.grpc"
      - "GrpcSettings:BankUrl=http://bank.grpc"
      - "GrpcSettings:UserUrl=http://user.grpc"
    ports:
      - "8002:80"
    depends_on:
      - oracle_rest_data_service
      - elasticsearch
      - rabbitmq
    networks:
      - elastic
      - ords_net
      - rabbitmq_go_net
      - gateway_net 

  account.grpc:
    container_name: account.grpc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OrdsSettings:Uri=http://oracle_rest_data_service:8080/ords/ordsuser/account/"
      - "OrdsSettings:DatabaseUrl=http://oracle_rest_data_service:8080"
      - "OrdsSettings:DatabaseUser=ordsuser"
      - "OrdsSettings:DatabaseTableName=account"
    ports:
      - "8003:80"
    depends_on:
      - oracle_rest_data_service
    networks:
      - ords_net
      - gateway_net 

  transaction.api:
    container_name: transaction.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OracleSettings:OrdsDatabaseUrl=http://oracle_rest_data_service:8080"
      - "OracleSettings:DatabaseUser=ordsuser"
      - "OracleSettings:DatabaseTableName=transaction"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672/"
      - "GrpcSettings:AccountUrl=http://account.grpc"
    ports:
      - "8004:80"
    depends_on:
      - oracle_rest_data_service
      - elasticsearch
      - rabbitmq
    networks:
      - elastic
      - ords_net
      - rabbitmq_go_net
      - gateway_net 

  statement.api:
    container_name: statement.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OracleSettings:OrdsDatabaseUrl=http://oracle_rest_data_service:8080"
      - "OracleSettings:DatabaseUser=ordsuser"
      - "OracleSettings:DatabaseTableName=transaction"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672/"
      - "GrpcSettings:BranchUrl=http://branch.grpc"
      - "GrpcSettings:AccountUrl=http://account.grpc"
    ports:
      - "8005:80"
    depends_on:
      - oracle_rest_data_service
      - elasticsearch
      - rabbitmq
    networks:
      - elastic
      - ords_net
      - rabbitmq_go_net
      - gateway_net

  identity.api:
    container_name: identity.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672/"
      - "ConnectionStrings:AuthConnectionString=Server=identityDb;Database=UserDb;User Id=sa;Password=Identity2024@Pass;"
    depends_on:
      - identityDb
      - elasticsearch
      - rabbitmq
    ports:
      - "8008:80"
    networks:
      - identity_net
      - elastic
      - gateway_net
      - rabbitmq_go_net

  ocelotapigw:
    container_name: ocelotapigw
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityUrl=http://identity.api" 
    depends_on:
      - branch.api
      - account.api
      - transaction.api
      - statement.api
      - identity.api
      - bank.api
      - account.access.api
      - agreement.api
    ports:
      - "8010:80"
    networks:
      - gateway_net


  account.access.api:
    container_name: account.access.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OracleSettings:OrdsDatabaseUrl=http://oracle_rest_data_service:8080"
      - "OracleSettings:DatabaseUser=ordsuser"
      - "OracleSettings:DatabaseTableName=account_access"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672/"
      - "GrpcSettings:AccountUrl=http://account.grpc"
      - "GrpcSettings:BankUrl=http://bank.grpc"
    ports:
      - "8006:80"
    depends_on:
      - oracle_rest_data_service
      - elasticsearch
      - rabbitmq
    networks:
      - ords_net
      - elastic
      - gateway_net
      - rabbitmq_go_net

  agreement.api:
    container_name: agreement.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OracleSettings:OrdsDatabaseUrl=http://oracle_rest_data_service:8080"
      - "OracleSettings:DatabaseUser=ordsuser"
      - "OracleSettings:DatabaseTableName=account_access"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "GrpcSettings:AccountUrl=http://account.grpc"
    ports:
      - "8007:80"
    depends_on:
      - oracle_rest_data_service
      - elasticsearch
    networks:
      - ords_net
      - elastic
      - gateway_net


  user.grpc:
    container_name: user.grpc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:AuthConnectionString=Server=identityDb;Database=UserDb;User Id=sa;Password=Identity2024@Pass;"
    depends_on:
      - identityDb 
    ports:
      - "8009:80"
    networks:
      - identity_net
      - gateway_net 


  bank.api:
    container_name: bank.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OrdsSettings:Uri=http://oracle_rest_data_service:8080/ords/ordsuser/bank/"
      - "OrdsSettings:DatabaseUrl=http://oracle_rest_data_service:8080"
      - "OrdsSettings:DatabaseUser=ordsuser"
      - "OrdsSettings:DatabaseTableName=bank"
    depends_on:
      - oracle_rest_data_service
    ports:
      - "8011:80"
    networks:
      - ords_net
      - gateway_net 


  bank.grpc:
    container_name: bank.grpc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OrdsSettings:Uri=http://oracle_rest_data_service:8080/ords/ordsuser/bank/"
      - "OrdsSettings:DatabaseUrl=http://oracle_rest_data_service:8080"
      - "OrdsSettings:DatabaseUser=ordsuser"
      - "OrdsSettings:DatabaseTableName=bank"
    depends_on:
      - oracle_rest_data_service
    ports:
      - "8012:80"
    networks:
      - ords_net
      - gateway_net 

