version: '3.4'

services:
  identityDb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  rabbitmq:
    image: rabbitmq:3-management
  
  portainer:
    image: portainer/portainer-ce

  branch.api:
    image: ${DOCKER_REGISTRY-}branchapi
    build:
      context: .
      dockerfile: Services/Branch/Branch.API/Dockerfile

  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Account/Account.API/Dockerfile


  account.grpc:
    image: ${DOCKER_REGISTRY-}accountgrpc
    build:
      context: .
      dockerfile: Services/Account/Account.Grpc/Dockerfile

  transaction.api:
    image: ${DOCKER_REGISTRY-}transactionapi
    build:
      context: .
      dockerfile: Services/Transaction/Transaction.API/Dockerfile

  statement.api:
    image: ${DOCKER_REGISTRY-}statementapi
    build:
      context: .
      dockerfile: Services/Statement/Statement.API/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Security/Identity.API/Dockerfile

  account.access.api:
    image: ${DOCKER_REGISTRY-}accountaccessapi
    build:
      context: .
      dockerfile: Services/AccountAccess/Account.Access.API/Dockerfile

  agreement.api:
    image: ${DOCKER_REGISTRY-}agreementapi
    build:
      context: .
      dockerfile: Services/Agreement/Agreement.API/Dockerfile

  user.grpc:
    image: ${DOCKER_REGISTRY-}usergrpc
    build:
      context: .
      dockerfile: Services/User/User.grpc/Dockerfile

  bank.api:
    image: ${DOCKER_REGISTRY-}bankapi
    build:
      context: .
      dockerfile: Services/Bank/Bank.api/Dockerfile

  bank.grpc:
    image: ${DOCKER_REGISTRY-}bankgrpc
    build:
      context: .
      dockerfile: Services/Bank/Bank.grpc/Dockerfile

  view.grpc:
    image: ${DOCKER_REGISTRY-}viewgrpc
    build:
      context: .
      dockerfile: Services/AccountAccess/View.grpc/Dockerfile

  notification.api:
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile

  branch.grpc:
    image: ${DOCKER_REGISTRY-}branchgrpc
    build:
      context: .
      dockerfile: Services/Branch/Branch.GRPC/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGW/Dockerfile

networks:
  elastic:
    driver: bridge
  rabbitmq_go_net:
    driver: bridge
  gateway_net:
    driver: bridge
  identity_net:
    driver: bridge
volumes:
  elasticsearch-data:
  portainer_data:




















